consul:
  token: 
election:
  enabled:
    - my_service
  services:
    my_service:
      id: my_service1
      kv: service/my_service
      token: 
      checks:
        - service:election1
      primaryTag: primary
      onPromote: '/usr/bin/printf promote'
      onDemote: '/usr/bin/printf demote'
